apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarqube
  name: sonar
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9000
      name: sonarqube
  selector:
    app: sonarqube
